stages:
  extract:
    cmd: python extract_dataframe.py

    deps: 
      - data/global_twitter_Data.json
    
    params:
      - extract_params.yml
    
    outs:
      - data/processed_global_tweet_data_dvc_pp.json

  clean_preprocess:
    cmd: python clean_tweets_dataframe.py

    deps:
      - data/processed_global_tweet_data.csv

    params:
      - clean_params.yml

    outs: 
      - data/clean_data_dvc_pp.json
      - data/clean_data_dvc_pp.csv

  populate_database:
    cmd: python MlOps-Modules/data_handler.py

    deps:
      - MlOps-Modules/create_table.sql

    params:
      - populate_db.yml

    outs:
      - MlOps-Modules/tweets.db
